### ISSUE TITLE
Support GitHub CLI for Dependabot automations

### ISSUE THREAD

**Issue by kimnh-0823** [sun-asterisk-research/actions-runner#10]
## Actually

Example Workflow:
```yaml
name: Dependabot auto-approve
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

Current result:
```bash
Run gh pr review --approve "$PR_URL"
line 1: gh: command not found
```

## Expect

The command `gh pr review --approve` will be completed successfully.
